config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  resources :despesas
  resources :receitas
  resources :saldos 

  root 'saldos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/despesa.rb
class Despesa < ApplicationRecord
    belongs_to :saldo
end

app/models/receitum.rb
class Receitum < ApplicationRecord
    belongs_to :saldo
end

app/models/saldo.rb
class Saldo < ApplicationRecord
    has_many :despesas
    has_many :receitas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/despesas_controller.rb
class DespesasController < ApplicationController
    
    def index
        @despesa = Despesa.all
    end

    def show
    end

    def new
    end

    def create
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private

    def set_dispesa
    end

    def despesa_params
    end
end

app/controllers/receitas_controller.rb
class ReceitasController < ApplicationController
end

app/controllers/saldos_controller.rb
class SaldosController < ApplicationController

    def index
        @saldo = Saldo.first || Saldo.create(valor: 0)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/despesas_helper.rb
module DespesasHelper
end

app/helpers/receitas_helper.rb
module ReceitasHelper
end

app/helpers/saldos_helper.rb
module SaldosHelper
end

app/views/despesas/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col" class="text-center">Descrição</th>
      <th scope="col" class="text-center">Valor</th>
      <th scope="col" class="text-center"></th>
    </tr>
  </thead>
  <tbody>
    <% @despesas.each do |despesa| %>
      <tr>
        <%# <th scope="row">1</th> %>
        <td class="align-middle text-center"><%= despesa.destricao %></td>
        <td class="align-middle text-center"><%= despesa.valor %></td>
        <td>
          <%= link_to 'Mostrar', despesa %>
          <%= link_to 'Editar', edit_despesa_path(despesa)%>
          <%= link_to 'Excluir', despesa, method: :delete, data: { turbo_method: :delete } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Nova Despesa'%>

app/views/despesas/show.html.erb
<p>Despesa</p>

<p><strong>Descrição: </strong> <%= @despesa.descricao %></p>
<p><strong>Valor: </strong> <%= @despesa.valor %></p>

<%= link_to 'Voltar', despesas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finance APP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%# BOOTSTRAP %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%# JS %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/receitas/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col" class="text-center">Descrição</th>
      <th scope="col" class="text-center">Valor</th>
      <th scope="col" class="text-center"></th>
    </tr>
  </thead>
  <tbody>
    <% @receitas.each do |receita| %>
      <tr>
        <%# <th scope="row">1</th> %>
        <td class="align-middle text-center"><%= despesa.destricao %></td>
        <td class="align-middle text-center"><%= despesa.valor %></td>
        <td>
          <%= link_to 'Mostrar', receita %>
          <%= link_to 'Editar', edit_despesa_path(receita)%>
          <%= link_to 'Excluir', receita, method: :delete, data: { turbo_method: :delete } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Nova Despesa'%>

app/views/receitas/show.html.erb
<p>Receita</p>

<p><strong>Descrição: </strong> <%= @receita.descricao %></p>
<p><strong>Valor: </strong> <%= @receita.valor %></p>

<%= link_to 'Voltar', receitas_path %>

app/views/saldos/index.html.erb
<p>Saldo Atual</p>
<p><strong>Valor:</strong> <%= @saldo.valor %></p>

<%= link_to 'Nova Despesa', new_despesa_path %>
<%= link_to 'Nova Receita', new_receita_path %>